services:
  - type: web
    name: telegram-bot-udyat
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        value: "8269017403:AAGImHTvPFPzStT4rQMxcuL6Nk6BWN9Qvyw"
      - key: APP_URL
        value: "https://telegram-bot-udyat.onrender.com"
          


